import { create, inspire, scale, start } from 'src/assets/images';

const modules = {
  inspire: {
    image: inspire.src,
    desc: '<p><strong>SELF-DISCOVERY, CAREER SENSITISATION, EMPLOYMENT AND ENTREPRENEURSHIP DEVELOPMENT</strong></p></br> The INSPIRE module is about the economy and employment options.This includes employment, entrepreneurship, and self- employment.Participants will be introduced to various strategies and tools that will help them to make informed decisions about future career paths.There are a lot of practical guidance that takes participants through the  process, from the first job interview to the first day on the new job and to managing  finances going forward.Participants learn how to market themselves and develop the  necessary documentation such as CVs and cover letters.',
  },
  create: {
    image: create.src,
    desc: '<p><strong>BASIC ENTREPRENEURSHIP, IDEATION AND BUSINESS MODEL CANVASS</strong></p> </br> During the CREATE module, trainees begin to walk through the business development  process, from business ‘Ideation’ to enterprise ‘realisation’. Solutions driven enterprises carry right values of the business idea and reach beyond the bottom line. Creative approaches such as design thinking, prototyping and product development, are explored to aid the ideation process. Tools and strategies such as the Business Model Canvas (BMC) and the introduction to business development support services provide the foundation needed by MSMEs. This module includes a full overview of the market research process, allowing trainees to pivot their ideas based on feedback received from the market. The understanding of how organisations work is created. Participants will appreciate the importance of the relationship between costing and pricing and have a grasp of basic financial management. There is an introduction on understanding how to finance the enterprise through capital, pricing, and revenue, as well as a section dedicated to learning to present and validate their business idea. At the end of the Module, MSMEs would have been able to develop a well-structured and validated BMC.',
  },
  start: {
    image: start.src,
    desc: '<p><strong>BUSINESS PLANNING, FINANCIAL PROJECTION, PREPARATION AND PITCHING</strong></p></br>The START module takes participants through the process of building their own enterprise based on a robust business plan. They are equipped on how to devise an economic and marketing plan with emphasis on digital marketing. Participants get to understand that Production, Operations, Organisation and Management plans are key to successfully rolling out an enterprise. Critical success-factor topics such as access to finance and access to financial services, access to markets and business development support services are extensively treated in the module. Only then will it be possible to START the enterprise on the best possible footing, and with the right systems in place. Emerging entrepreneurs will value the importance of having their enterprise registered and having a business focus bank account.',
  },
  scale: {
    image: scale.src,
    desc: '<p><strong>BUSINESS INNOVATION, PRODUCTIVITY ENHANCEMENT AND GROWTH PLANNING TOWARDS INCREASED INVESTMENT</strong></p></br>During the SCALE module, participants will acquire capacity to successfully pitch to potential investors. Hence at the end of the module each emerging entrepreneur will pitch their business plan. The SCALE module teaches participants how to grow their business to take it from strength to strength. It includes different strategies for encouraging creativity, innovation, and collaboration between the business owner and the team members. Staff are the backbone of every MSME, and this module will teach how to best manage the entire process, from recruitment to onboarding,  to keeping everyone motivated. Participants will learn how to access specific support for innovation. Growth will be key and the Balanced Scorecard as a framework for growth mapping will be learn. Participants will learn about digital marketing and how to deliver a successful digital marketing campaign as well as embracing e-commerce. Technology is an important component, and this module teaches the different types of technologies participants should consider using to keep their business competitive. The SCALE module teaches how to assess performance and productivity and garner customer feedback for further optimisation of MSME. An important component of this is learning how to embed Quality Management Practices into the business and other due diligence processes, such as contract management and good corporate citizenship. Finally, the SCALE module equips participants to be leaders as they learn different skills such as pitching to investors, financing growth, and formulating a growth plan.',
  },
};
export const intro =
  'The THRIVE Entrepreneurship Development Programme - <strong>"Creating Business Development Opportunities through Entrepreneurship Training, Coaching and linkage Measures.”</strong> The trainings are delivered using the blended learning model of combining online and in-person trainings. The content of the training has been designed to be rolled out using a modular approach that builds from INSPIRE, to CREATE, to START, and ends with the SCALE module.';

export default modules;
